### ISSUE TITLE
Wrong Quick Start URL on the Home Page

### ISSUE THREAD

**Issue by aligoren** [pavjacko/renative#466] opened 2020-04-16 18:45 UTC
https://github.com/pavjacko/renative/blob/4f117d4a607af601aa509adf14ede17db2f21239/website/pages/en/index.js#L100

## Description

The quick start URL on the home page is redirected to the wrong address.

## Steps to Reproduce Bug

I visited [ReNative](https://renative.org/) website

I clicked **Try It Out**.

I redirected `/docs/quickstart` and I get 404 error.

## Expected Behavior

The quickstart url should be redirected to `/docs/intro-quickstart`

**Comment by CHaNGeTe** [comment] 2020-04-16 19:41
Duplicate of https://github.com/pavjacko/renative/issues/460

But I close mine as yours have better desc :)

**Comment by aligoren** [comment] 2020-04-16 20:10
> Duplicate of #460
> 
> But I close mine as yours have better desc :)

I'm so sorry, I didn't see your issue :/

If you want to fix this issue you can send a PR. Or I can do (:

Thanks

**Comment by YuviGold** [comment] 2020-05-09 15:27
Seems to be fixed on commit 8061c470

**Closed** 2020-12-26 06:49 UTC
Labels: wontfix
