### ISSUE TITLE
RNV 0.26.0-alpha5 creates empty folder instead of a project

### ISSUE THREAD

**Issue by lukebars** [pavjacko/renative#201] opened 2019-08-22 08:11 UTC
```
 ❓ Is All Correct? (press ENTER for yes)
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  ReNative Project Generator                                              │
│  undefined                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│                                                                              │
│  Project Name (folder): rnvalphatest                                         │
│  Project Title: rnvalphatest                                                 │
│  Project Version: 0.1.0                                                      │
│  App ID: com.mycompany.rnvalphatest                                          │
│  Project Template: renative-template-hello-world                             │
│                                                                              │
│  Project Platforms:                                                          │
│  ios, android, androidtv, web                                                │
│                                                                              │
│  Project Structure:                                                          │
│                                                                              │
│  rnvalphatest                                                                │
│   ├── appConfigs           # Application flavour configuration files/assets  │
│   │   └── default          # Example application flavour                     │
│   │       ├── assets       # Platform assets injected to ./platformAssets    │
│   │       ├── builds       # Platform files injected to ./platformBuilds     │
│   │       └── renative.json  # Application flavour config                      │
│   ├── platformAssets       # Generated cross-platform assets                 │
│   ├── platformBuilds       # Generated platform app projects                 │
│   ├── projectConfigs       # Project configuration files/assets              │
│   │   ├── fonts            # Folder for all custom fonts                     │
│   │   ├── permissions.json # Permissions configuration                       │
│   │   └── plugins.json     # Multi-platform Plugins configuration            │
│   ├── src                  # Source files                                    │
│   ├── index.*.js           # Entry files                                     │
│   └── renative.json      # ReNative project configuration                  │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
: 
✅ Your project is ready! navigate to project cd rnvalphatest and run rnv run -p web to see magic happen!

 $ rnv new - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 8/22/2019, 11:09:43 AM                                        │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  App Config: undefined                                                       │
│  Env Info: darwin | x64 | node v11.11.0 | rnv vundefined                     │
│  Executed Time: 0h:0m:22s:574ms                                              │
│                                                                              │
│ ⚠️  $ rnv new - WARNING: loadFile: Path /Users/luke/Desktop/platformBuilds/renative.build.json does not exists!
│ ⚠️  $ rnv new - WARNING: loadFile: Path /Users/luke/Desktop/renative.json does not exists!
│ ⚠️  $ rnv new - WARNING: loadFile: Path /Users/luke/Desktop/renative.local.json does not exists!
│ ⚠️  $ rnv new - WARNING: loadFile: Path /Users/luke/Desktop/renative.private.json does not exists!
│ ✅ Your project is ready! navigate to project cd rnvalphatest and run rnv run -p web to see magic happen!
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
$ cd rnvalphatest/
$ rnv start

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv start                                                           │
│        Start Time: 8/22/2019, 11:09:54 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

$ rnv start - initializeBuilder - Starting!
⚠️  $ rnv start - WARNING: Error: ENOENT: no such file or directory, scandir '/Users/luke/Desktop/rnvalphatest/appConfigs'
⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/platformBuilds/renative.build.json does not exists!
⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/renative.json does not exists!
⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/renative.local.json does not exists!
⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/renative.private.json does not exists!
$ rnv start - _generateBuildConfig - Starting!
$ rnv start - _generateBuildConfig:14:3:0:0 - Starting!
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 8/22/2019, 11:09:54 AM                                        │
│  $ rnv start                                                                 │
├──────────────────────────────────────────────────────────────────────────────┤
│  App Config: undefined                                                       │
│  Env Info: darwin | x64 | node v11.11.0 | rnv vundefined                     │
│  Executed Time: 0h:0m:0s:12ms                                                │
│                                                                              │
│ ⚠️  $ rnv start - WARNING: Error: ENOENT: no such file or directory, scandir '/Users/luke/Desktop/rnvalphatest/appConfigs'
│ ⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/platformBuilds/renative.build.json does not exists!
│ ⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/renative.json does not exists!
│ ⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/renative.local.json does not exists!
│ ⚠️  $ rnv start - WARNING: loadFile: Path /Users/luke/Desktop/rnvalphatest/renative.private.json does not exists!
│ 🛑  $ rnv start - ERRROR! Looks like this directory is not ReNative project. Project config /Users/luke/Desktop/rnvalphatest/renative.json is missing!. You can create new project with rnv new
```

same applies for alpha 5

**Comment by pavjacko** [comment] 2019-08-22 08:26
`0.26.0-alphaXXX` is not stable yet. please use `0.25.x` untile stable non alpha of `0.26.0` is out (planned for today). duplicate of #197

**Closed** 2019-08-29 08:44 UTC
Labels: wontfix
