### ISSUE TITLE
RNV 0.26.0-alpha5 running rnv run -p androidtv opens and then crashes the emulator 

### ISSUE THREAD

**Issue by lukebars** [pavjacko/renative#202] opened 2019-08-22 08:13 UTC
No build errors, runs fine if the emulator is open prior to `rnv run -p androidtv` .

**Comment by pavjacko** [comment] 2019-08-22 08:26
`0.26.0-alphaXXX` is not stable yet. please use `0.25.x` until stable non alpha of `0.26.0` is out (planned for today). duplicate of #197

**Closed** 2019-08-29 08:44 UTC
Labels: wontfix
